# -*- coding: utf-8 -*-
"""Untitled7.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oOJ-F2XBkOWHA279F_HCYYecXiag4A03

STOCHASTIC GRADIENT DESCENT
"""

from sklearn.datasets import load_diabetes
import pandas as pd

data = load_diabetes()

X = pd.DataFrame(data.data, columns=data.feature_names)
y = pd.Series(data.target, name="target")

df = pd.concat([X, y], axis=1)

print(df.head())
print(df.shape)

print(df.info())
print(df.describe())
print(df.isnull().sum())

import matplotlib.pyplot as plt

plt.figure(figsize=(8,5))
plt.hist(df["target"], bins=30)
plt.xlabel("Disease Progression")
plt.ylabel("Frequency")
plt.title("Distribution of Target Variable")
plt.show()

df.hist(figsize=(14,10), bins=30)
plt.tight_layout()
plt.show()

features = X.columns

for feature in features:
    plt.figure(figsize=(6,4))
    plt.scatter(df[feature], df["target"], alpha=0.5)
    plt.xlabel(feature)
    plt.ylabel("target")
    plt.title(f"{feature} vs Target")
    plt.show()

corr = df.corr()

plt.figure(figsize=(10,8))
plt.imshow(corr, cmap="coolwarm", interpolation="none")
plt.colorbar()

plt.xticks(range(len(corr.columns)), corr.columns, rotation=45)
plt.yticks(range(len(corr.columns)), corr.columns)

plt.title("Correlation Matrix")
plt.tight_layout()
plt.show()

target_corr = df.corr()["target"].sort_values(ascending=False)

print(target_corr)

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

# Mean and standard deviation from training data only
import numpy as np

mean = np.mean(X_train, axis=0)
std = np.std(X_train, axis=0)

X_train_scaled = (X_train - mean) / std
X_test_scaled = (X_test - mean) / std

print("Mean shape:", mean.shape)
print("Std shape :", std.shape)

print("\nFirst 5 rows after scaling:")
print(X_train_scaled[:5])

n_features = X_train_scaled.shape[1]

w = np.zeros(n_features)
b = 0.0

print("Weights shape:", w.shape)
print("Weights:", w)
print("Bias:", b)

learning_rate = 0.01
batch_size = 32
epochs = 1000

print("Learning Rate:", learning_rate)
print("Batch Size:", batch_size)
print("Epochs:", epochs)

n_samples = X_train_scaled.shape[0]

indices = np.random.permutation(n_samples)

X_shuffled = X_train_scaled.iloc[indices]
y_shuffled = y_train.iloc[indices]

print("Original samples:", n_samples)
print("Shuffled X shape:", X_shuffled.shape)
print("Shuffled y shape:", y_shuffled.shape)

X_shuffled = X_train_scaled.iloc[indices]
y_shuffled = y_train.iloc[indices]
X_shuffled
y_shuffled

start = 0
end = start + batch_size

X_batch = X_shuffled[start:end]
y_batch = y_shuffled[start:end]

print("X_batch shape:", X_batch.shape)
print("y_batch shape:", y_batch.shape)

y_pred = X_batch @ w + b

print("y_pred shape:", y_pred.shape)
print("First 5 predictions:", y_pred[:5])
print("First 5 actual values:", y_batch[:5])

errors = y_pred - y_batch

squared_errors = errors ** 2

loss = np.mean(squared_errors)

print("Loss:", loss)

m = len(y_batch)

dw = (2 / m) * (X_batch.T @ (y_pred - y_batch))

db = (2 / m) * np.sum(y_pred - y_batch)

print("dw shape:", dw.shape)
print("dw:", dw)

print("\ndb:", db)

learning_rate = 0.01

w = w - learning_rate * dw
b = b - learning_rate * db

print("Updated weights:")
print(w)

print("\nUpdated bias:")
print(b)

learning_rate = 0.001

w = np.zeros(n_features)
b = 0.0

loss_history = []

n_samples = X_train_scaled.shape[0]

for epoch in range(epochs):

    indices = np.random.permutation(n_samples)

    X_shuffled = X_train_scaled.iloc[indices]
    y_shuffled = y_train.iloc[indices]

    epoch_loss = 0
    total_samples = 0

    for start in range(0, n_samples, batch_size):

        end = start + batch_size

        X_batch = X_shuffled[start:end]
        y_batch = y_shuffled[start:end]

        # Forward pass
        y_pred = X_batch @ w + b

        # Error and loss
        error = y_pred - y_batch
        loss = np.mean(error ** 2)

        # Gradients
        m = len(y_batch)

        dw = (2 / m) * (X_batch.T @ error)
        db = (2 / m) * np.sum(error)

        # Update
        w = w - learning_rate * dw
        b = b - learning_rate * db

        # Weighted loss accumulation
        epoch_loss += loss * m
        total_samples += m

    epoch_loss = epoch_loss / total_samples

    loss_history.append(epoch_loss)

    if (epoch + 1) % 100 == 0:
        print(f"Epoch {epoch + 1}, Loss: {epoch_loss:.4f}")

plt.figure(figsize=(8, 5))

plt.plot(loss_history)

plt.xlabel("Epoch")
plt.ylabel("MSE Loss")
plt.title("Mini-Batch Gradient Descent")

plt.grid(True)
plt.show()

y_test_pred = X_test_scaled @ w + b

test_error = y_test_pred - y_test

test_mse = np.mean(test_error ** 2)

print("Test MSE:", test_mse)

plt.figure(figsize=(7, 6))

plt.scatter(y_test, y_test_pred, alpha=0.7)

# Perfect prediction line
min_value = min(y_test.min(), y_test_pred.min())
max_value = max(y_test.max(), y_test_pred.max())

plt.plot(
    [min_value, max_value],
    [min_value, max_value],
    linestyle="--"
)

plt.xlabel("Actual Values")
plt.ylabel("Predicted Values")
plt.title("Actual vs Predicted")

plt.grid(True)
plt.show()

y_mean = np.mean(y_test)

ss_total = np.sum((y_test - y_mean) ** 2)

ss_residual = np.sum((y_test - y_test_pred) ** 2)

r2 = 1 - (ss_residual / ss_total)

print("R² Score:", r2)

residuals = y_test - y_test_pred

plt.figure(figsize=(8, 5))

plt.scatter(y_test_pred, residuals, alpha=0.7)

plt.axhline(0, linestyle="--")

plt.xlabel("Predicted Values")
plt.ylabel("Residuals")
plt.title("Residual Plot")

plt.grid(True)
plt.show()

"""IMPLEMENT MINI BATCH FROM SCRATCH USING CLASS

"""

import numpy as np


class MiniBatchGradientDescent:

    def __init__(self, learning_rate=0.005, batch_size=32, epochs=1000):
        self.learning_rate = learning_rate
        self.batch_size = batch_size
        self.epochs = epochs

        self.w = None
        self.b = 0.0
        self.loss_history = []

    def fit(self, X, y):

        n_samples, n_features = X.shape

        # Initialize parameters
        self.w = np.zeros(n_features)
        self.b = 0.0

        self.loss_history = []

        for epoch in range(self.epochs):

            # Shuffle data
            indices = np.random.permutation(n_samples)

            X_shuffled = X.iloc[indices]
            y_shuffled = y.iloc[indices]

            total_loss = 0
            total_samples = 0

            # Create mini-batches
            for start in range(0, n_samples, self.batch_size):

                end = start + self.batch_size

                X_batch = X_shuffled[start:end]
                y_batch = y_shuffled[start:end]

                # Forward pass
                y_pred = X_batch @ self.w + self.b

                # Error
                error = y_pred - y_batch

                # Loss
                loss = np.mean(error ** 2)

                # Gradients
                m = len(y_batch)

                dw = (2 / m) * (X_batch.T @ error)
                db = (2 / m) * np.sum(error)

                # Parameter update
                self.w = self.w - self.learning_rate * dw
                self.b = self.b - self.learning_rate * db

                # Weighted loss
                total_loss += loss * m
                total_samples += m

            # Average epoch loss
            epoch_loss = total_loss / total_samples

            self.loss_history.append(epoch_loss)

            if (epoch + 1) % 100 == 0:
                print(
                    f"Epoch {epoch + 1}, "
                    f"Loss: {epoch_loss:.4f}"
                )

        return self

    def predict(self, X):

        return X @ self.w + self.b

    def mse(self, y_true, y_pred):

        return np.mean((y_true - y_pred) ** 2)

    def r2_score(self, y_true, y_pred):

        ss_total = np.sum((y_true - np.mean(y_true)) ** 2)
        ss_residual = np.sum((y_true - y_pred) ** 2)

        return 1 - (ss_residual / ss_total)

model = MiniBatchGradientDescent(
    learning_rate=0.005,
    batch_size=32,
    epochs=1000
)


model.fit(X_train_scaled, y_train)

y_test_pred = model.predict(X_test_scaled)

mse = model.mse(y_test, y_test_pred)
r2 = model.r2_score(y_test, y_test_pred)

print("Test MSE:", mse)
print("R² Score:", r2)

plt.figure(figsize=(8, 5))

plt.plot(model.loss_history)

plt.xlabel("Epoch")
plt.ylabel("MSE Loss")
plt.title("Mini-Batch Gradient Descent Loss Curve")

plt.grid(True)
plt.show()

